#!/usr/bin/env bash
# Regression test: AGENTS.md is the project's only instruction file and its DevKit block
# loads the DevKit essentials, the active profile's rules and the project rules index,
# whatever the project already had:
#   - no AGENTS.md: a project AGENTS.md is written (not the master link), no CLAUDE.md
#   - its own AGENTS.md with CLAUDE.md -> AGENTS.md: AGENTS_old.md is made, the link goes,
#     one block in the one file; the master stays reachable at .agents/devkit/AGENTS.md
#   - its own CLAUDE.md: the text moves into AGENTS.md, the original is CLAUDE_old.md
#   - the profile rules (.agents/context/profile-rules.md) follow `agent-kit profile`
# and every @-import of the block is a real file inside the project (an import through
# a link out of the project is not loaded by Claude Code / Gemini CLI).
set -u

DEVKIT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
export DEVKIT_LANG=en
unset CLAUDE_PROJECT_DIR TARGET_DIR DEVKIT_PROFILE

FAILS=0
ok() { echo "✔ $1"; }
fail() { echo "✖ $1"; FAILS=$((FAILS + 1)); }
install() { bash "$DEVKIT_DIR/bin/install.sh" -t "$1" -a claude -y --no-githooks "${@:2}" > "$TMP/out" 2>&1 || { fail "install exited non-zero"; tail -5 "$TMP/out"; }; }
block() { sed -n '/universal-agent-devkit:start/,/universal-agent-devkit:end/p' "$1"; }
unresolved() { # <project> <file> — @-imports of the DevKit block that are not real files inside <project>
  block "$1/$2" | grep -o '@[^ `)]*' | sed 's/^@//' | while read -r f; do
    [ -f "$1/$f" ] && python3 -c 'import os,sys; sys.exit(0 if os.path.realpath(sys.argv[2]).startswith(os.path.realpath(sys.argv[1]) + os.sep) else 1)' "$1" "$1/$f" || echo "$f"
  done; }
body_of() { grep -v '^<!-- Generated by Universal Agent DevKit' "$1"; }

# --- no AGENTS.md, profile android ---------------------------------------------------
A="$TMP/a"; mkdir -p "$A" && (cd "$A" && git init -q)
install "$A" -p android
[ -f "$A/AGENTS.md" ] && [ ! -L "$A/AGENTS.md" ] && [ ! -e "$A/CLAUDE.md" ] && block "$A/AGENTS.md" | grep -q '@.agents/context/essentials.md' \
  && ok "no AGENTS.md: a project AGENTS.md with the block, no CLAUDE.md" || fail "AGENTS.md: $(ls -la "$A" | grep -E 'AGENTS|CLAUDE')"
block "$A/AGENTS.md" | grep -q '@.agents/context/profile-rules.md' && [ "$(body_of "$A/.agents/context/profile-rules.md")" = "$(cat "$DEVKIT_DIR/profiles/android/RULES.md")" ] \
  && ok "profile rules loaded from .agents/context/profile-rules.md (a copy of android RULES.md)" || fail "profile rules import missing"
[ "$(body_of "$A/.agents/context/essentials.md")" = "$(cat "$DEVKIT_DIR/rules/essentials.md")" ] && ok "essentials.md is the DevKit's rules/essentials.md" || fail "essentials copy differs"
[ -z "$(unresolved "$A" AGENTS.md)" ] && ok "every @-import in AGENTS.md is a real file in the project" || fail "not loadable: $(unresolved "$A" AGENTS.md | tr '\n' ' ')"
[ -L "$A/.agents/devkit" ] && [ -f "$A/.agents/devkit/rules/core-rules.md" ] && [ ! -e "$A/rules" ] && [ ! -e "$A/skills" ] && [ ! -e "$A/commands" ] \
  && ok ".agents/devkit reaches the DevKit; no rules/ skills/ commands/ at the root" || fail "layout: $(ls -A "$A" | tr '\n' ' ')"
[ -f "$A/.agents/active-profile.json" ] && [ ! -e "$A/.active-profile.json" ] && ok "profile state in .agents/active-profile.json" || fail "profile state file misplaced"
cmp -s "$A/DESIGN.md" "$DEVKIT_DIR/profiles/android/DESIGN.md" && ok "DESIGN.md is the android profile's, not the generic template" || fail "profile DESIGN.md not used"
! grep -q 'INSTINCT-V0' "$A/.agents/instincts.md" && ok "the new instincts.md carries no voice-assistant traps" || fail "voice traps seeded into an android project"

# --- the project's own AGENTS.md, CLAUDE.md links to it -------------------------------
B="$TMP/b"; mkdir -p "$B" && (cd "$B" && git init -q)
printf '# Our rules\n\n## 6. Ours\n- keep\n' > "$B/AGENTS.md"; ln -s AGENTS.md "$B/CLAUDE.md"
install "$B" -p web
[ "$(cat "$B/AGENTS_old.md" 2>/dev/null)" = "$(printf '# Our rules\n\n## 6. Ours\n- keep')" ] \
  && ok "CLAUDE.md -> AGENTS.md: the original AGENTS.md is kept as AGENTS_old.md" || fail "AGENTS_old.md missing or wrong"
[ ! -e "$B/CLAUDE.md" ] && [ ! -L "$B/CLAUDE.md" ] && ok "the CLAUDE.md link is removed (AGENTS.md is the only file)" || fail "CLAUDE.md link left"
[ "$(grep -c 'universal-agent-devkit:start' "$B/AGENTS.md")" = 1 ] && grep -q '^## 6. Ours' "$B/AGENTS.md" \
  && ok "one DevKit block in the shared file, the project's content kept" || fail "blocks: $(grep -c 'universal-agent-devkit:start' "$B/AGENTS.md")"
block "$B/AGENTS.md" | grep -q '.agents/devkit/AGENTS.md' && cmp -s "$B/.agents/devkit/AGENTS.md" "$DEVKIT_DIR/AGENTS.md" \
  && ok "own AGENTS.md: the master is reachable at .agents/devkit/AGENTS.md and named in the block" || fail "master not reachable"
block "$B/AGENTS.md" | grep -q '@AGENTS\.md' && fail "a self-import of AGENTS.md is left" || ok "no @AGENTS.md self-import"
block "$B/AGENTS.md" | grep -q 'python3 bin/post-fix-gate.py' && fail "gate command points at bin/ (not installed in projects)" || ok "gate command is one that exists in a project"
[ -z "$(unresolved "$B" AGENTS.md)" ] && ok "every @-import in AGENTS.md is a real file in the project" || fail "not loadable: $(unresolved "$B" AGENTS.md | tr '\n' ' ')"
install "$B" -p web
[ "$(grep -c 'universal-agent-devkit:start' "$B/AGENTS.md")" = 1 ] && [ ! -e "$B/AGENTS_old_"* ] 2>/dev/null \
  && ok "re-install: still one block, no second backup" || fail "re-install duplicated"

# --- the project's own CLAUDE.md is folded into AGENTS.md ------------------------------
D="$TMP/d"; mkdir -p "$D" && (cd "$D" && git init -q)
printf '# Project D\n\nFact: uses Kotlin 2.1.\n' > "$D/CLAUDE.md"
install "$D" -p none
[ ! -e "$D/CLAUDE.md" ] && grep -q 'Fact: uses Kotlin 2.1.' "$D/AGENTS.md" && grep -q 'Fact: uses Kotlin 2.1.' "$D/CLAUDE_old.md" \
  && ok "own CLAUDE.md: its text is in AGENTS.md, the original kept as CLAUDE_old.md" || fail "CLAUDE.md not folded"
[ "$(awk '/Fact: uses Kotlin/{f=NR} /universal-agent-devkit:start/{b=NR} END{print (f && b && f<b)}' "$D/AGENTS.md")" = 1 ] \
  && ok "the folded text sits above the DevKit block" || fail "folded text placement"
install "$D" -p none
[ "$(grep -c 'Fact: uses Kotlin 2.1.' "$D/AGENTS.md")" = 1 ] && ok "re-install does not fold the text twice" || fail "text folded twice"

# --- installed without a profile, then `agent-kit profile` ------------------------------
C="$TMP/c"; mkdir -p "$C" && (cd "$C" && git init -q)
install "$C" -p none
grep -q 'No domain profile is active' "$C/.agents/context/profile-rules.md" && ok "-p none: profile-rules.md says no profile is active" || fail "-p none profile rules: $(head -3 "$C/.agents/context/profile-rules.md")"
python3 "$DEVKIT_DIR/bin/agent-config.py" --profile backend --target "$C" >/dev/null 2>&1
python3 "$DEVKIT_DIR/bin/agent-config.py" --profile ios --target "$C" >/dev/null 2>&1
[ "$(block "$C/AGENTS.md" | grep -c '@.agents/context/profile-rules.md')" = 1 ] && [ "$(body_of "$C/.agents/context/profile-rules.md")" = "$(cat "$DEVKIT_DIR/profiles/ios/RULES.md")" ] \
  && ok "agent-kit profile: one import, and profile-rules.md follows the switch (ios)" || fail "profile switch: $(head -2 "$C/.agents/context/profile-rules.md" | tail -1)"
[ -z "$(unresolved "$C" AGENTS.md)" ] && ok "after the switch every @-import is loadable" || fail "not loadable: $(unresolved "$C" AGENTS.md | tr '\n' ' ')"

# --- a project .gitignore that hides .agents/ is reported with the fix ----------------
G="$TMP/g"; mkdir -p "$G" && (cd "$G" && git init -q) && printf '/.agents/\n' > "$G/.gitignore"
install "$G" -p none
grep -q "ignores .agents/instincts.md" "$TMP/out" && grep -q "'/.agents/\*'" "$TMP/out" \
  && ok ".gitignore hiding .agents/: warned, with the /.agents/* fix" || fail "no warning for an ignored .agents/"
grep -qx '/.agents/' "$G/.gitignore" && ok "the project's own ignore rule is left as it was" || fail "project rule edited"
H="$TMP/h"; mkdir -p "$H" && (cd "$H" && git init -q)
install "$H" -p none
grep -q "ignores .agents" "$TMP/out" && fail "warned without an ignore rule" || ok "no warning when .agents/ is not ignored"

# --- symlink mode: DevKit links are machine-local — kept out of git via .git/info/exclude
links_listed="$(cd "$A" && git ls-files -o --exclude-standard -z | xargs -0 -n1 sh -c '[ -L "$0" ] && readlink "$0"' 2>/dev/null | grep -c "$DEVKIT_DIR" || true)"
[ "$links_listed" = 0 ] && grep -q '^/.claude/hooks/precode_gate.sh$' "$A/.git/info/exclude" && grep -qx '/.agents/devkit' "$A/.git/info/exclude" \
  && ok "symlink mode: no DevKit link shows up as untracked (listed in .git/info/exclude)" || fail "$links_listed DevKit links still untracked"
[ -f "$A/.agents/instincts.md" ] && (cd "$A" && git ls-files -o --exclude-standard | grep -q '^.agents/instincts.md$') \
  && ok "the project's own files (instincts.md) still show up to be committed" || fail "instincts.md hidden"

# --- re-init with -y keeps the agents the project was set up for ------------------------
K="$TMP/k"; mkdir -p "$K" && (cd "$K" && git init -q)
bash "$DEVKIT_DIR/bin/install.sh" -t "$K" -a claude,gemini -p none -y --no-githooks >/dev/null 2>&1
bash "$DEVKIT_DIR/bin/install.sh" -t "$K" -p none -y --no-githooks > "$TMP/k.out" 2>&1
[ ! -e "$K/.codex" ] && [ ! -e "$K/.cursor" ] && [ ! -e "$K/.grok" ] && [ ! -e "$K/GEMINI.md" ] && grep -q '"AGENTS.md"' "$K/.gemini/settings.json" \
  && grep -q "keeping the agents already set up: claude,gemini" "$TMP/k.out" \
  && ok "re-init -y without -a keeps claude+gemini; removed Codex/Cursor do not come back" || fail "re-init re-added agents: $(ls -a "$K" | tr '\n' ' ')"
F="$TMP/f"; mkdir -p "$F" && (cd "$F" && git init -q)
bash "$DEVKIT_DIR/bin/install.sh" -t "$F" -p none -y --no-githooks >/dev/null 2>&1
[ -f "$F/.codex/hooks.json" ] && [ -f "$F/.cursor/hooks.json" ] && [ ! -e "$F/.grok" ] \
  && ok "a first install with -y still sets up every agent, and Grok adds no directory" || fail "first install missed agents"

# --- uninstall takes .agents/devkit and the generated context away -----------------------
python3 "$DEVKIT_DIR/scripts/devkit_uninstall.py" "$B" --apply >/dev/null 2>&1
[ ! -e "$B/.agents/devkit" ] && [ ! -L "$B/.agents/devkit" ] && [ ! -e "$B/.agents/context" ] \
  && ok "uninstall removes .agents/devkit and .agents/context" || fail "left after uninstall: $(ls -A "$B/.agents" 2>/dev/null | tr '\n' ' ')"
grep -q '^## 6. Ours' "$B/AGENTS.md" && ! grep -q 'universal-agent-devkit' "$B/AGENTS.md" && ok "uninstall keeps the project's AGENTS.md text, block gone" || fail "AGENTS.md after uninstall"

if [ "$FAILS" -ne 0 ]; then echo "injection block: $FAILS FAILED"; exit 1; fi
echo "injection block: all checks passed"
