#!/usr/bin/env python3
"""context_sync.py <project> [--check] [--quiet] — the files AGENTS.md loads at startup.

The DevKit block of a project's AGENTS.md imports three files from .agents/context/:

  essentials.md      rules/essentials.md of this DevKit (the always-on rules)
  profile-rules.md   the active profile's RULES.md (.agents/active-profile/RULES.md)
  rules-index.md     one line per section of the project's own rules (rules_index.py)

They are REAL files, written here, because Claude Code does not expand an `@` import
whose real path is outside the project unless the user has approved external imports
for that project (measured 2026-09-24: every import through a DevKit symlink was
silently skipped in all three migrated projects), and Gemini CLI refuses such paths as
path traversal. Generated, never committed (.gitignore: .agents/context/); re-written
by `agent-kit init`, `agent-kit profile`, the relink git hooks and SessionStart.

It also writes rules/essentials.md IN FULL between the devkit-essentials markers of the
project's AGENTS.md: Antigravity reads AGENTS.md as plain text and expands no `@` import at
all (measured 2026-09-25), so the essentials must be in the file itself. No markers, or an
AGENTS.md that is a symlink: left alone.

--check: exit 1 and name the stale files; nothing is written.
"""
import os
import sys

DEVKIT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, os.path.join(DEVKIT, "scripts"))
import rules_index  # noqa: E402

CONTEXT_DIR = os.path.join(".agents", "context")
HEADER = "<!-- Generated by Universal Agent DevKit from {src} — do not edit; re-run `agent-kit init`. -->\n"


def wanted(project):
    """{relative path: content} of every context file for <project>."""
    out = {}
    with open(os.path.join(DEVKIT, "rules", "essentials.md"), encoding="utf-8") as f:
        out["essentials.md"] = HEADER.format(src="rules/essentials.md") + f.read()
    rules = os.path.join(project, ".agents", "active-profile", "RULES.md")
    if os.path.isfile(rules):
        prof = os.path.basename(os.path.realpath(os.path.dirname(rules)))
        with open(rules, encoding="utf-8") as f:
            out["profile-rules.md"] = HEADER.format(src=f"profiles/{prof}/RULES.md") + f.read()
    else:
        out["profile-rules.md"] = HEADER.format(src="(no profile)") + \
            "No domain profile is active (`agent-kit profile <name>` sets one).\n"
    index = rules_index.build(project)
    out["rules-index.md"] = HEADER.format(src=".agents/local/rules/") + \
        (index or "No project rules yet (`.agents/local/rules/` is empty).\n")
    return out


MARK_START = "<!-- devkit-essentials:start"
MARK_END = "<!-- devkit-essentials:end -->"


BLOCK_START = "universal-agent-devkit:start"


def agents_md_wanted(project):
    """(path, current, wanted) for AGENTS.md with its essentials section refreshed, or None
    (no AGENTS.md, a symlink, not UTF-8). An older DevKit block without the markers gives
    wanted=None: only `agent-kit init` can add them, and --check says so."""
    path = os.path.join(project, "AGENTS.md")
    if os.path.islink(path):
        return None
    try:
        with open(path, encoding="utf-8", newline="") as f:
            text = f.read()
    except (OSError, UnicodeDecodeError):
        return None
    i = text.find(MARK_START)
    j = text.find(MARK_END, i) if i >= 0 else -1
    if i < 0 or j < 0:
        return (path, text, None) if BLOCK_START in text else None
    nl = "\r\n" if "\r\n" in text else "\n"
    eol = text.find("\n", i)
    keep = j if eol < 0 or eol > j else eol + 1     # markers on one line: insert before the end one
    head = text[:keep] if keep > i and text[keep - 1] == "\n" else text[:keep] + nl
    with open(os.path.join(DEVKIT, "rules", "essentials.md"), encoding="utf-8") as f:
        essentials = f.read().rstrip("\n") + "\n"
    return path, text, head + essentials.replace("\n", nl) + text[j:]


def stale(project):
    """Names of the context files that are missing or differ from what they should hold."""
    base = os.path.join(project, CONTEXT_DIR)
    bad = []
    for name, text in wanted(project).items():
        try:
            with open(os.path.join(base, name), encoding="utf-8") as f:
                if f.read() == text:
                    continue
        except OSError:
            pass
        bad.append(name)
    agents = agents_md_wanted(project)
    if agents and agents[2] is None:
        bad.append("AGENTS.md (DevKit block without the essentials section: re-run agent-kit init)")
    elif agents and agents[1] != agents[2]:
        bad.append("AGENTS.md")
    return bad


def sync(project, agents_md=True):
    """Write the stale files; return their names. agents_md=False (--context-only, the relink
    git hooks) leaves the tracked AGENTS.md alone right after a checkout."""
    base = os.path.join(project, CONTEXT_DIR)
    os.makedirs(base, exist_ok=True)
    changed = []
    for name, text in wanted(project).items():
        path = os.path.join(base, name)
        try:
            with open(path, encoding="utf-8") as f:
                if f.read() == text:
                    continue
        except OSError:
            pass
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
        changed.append(name)
    agents = agents_md_wanted(project) if agents_md else None
    if agents and agents[2] is not None and agents[1] != agents[2]:
        tmp = agents[0] + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline="") as f:
            f.write(agents[2])
        os.replace(tmp, agents[0])
        changed.append("AGENTS.md")
    old_index = os.path.join(project, ".agents", "local", "rules", rules_index.INDEX_NAME)
    if os.path.isfile(old_index) and rules_index.GENERATED_MARK in open(old_index, encoding="utf-8").read(200):
        os.unlink(old_index)            # where an early 1.3 build wrote the index
    return changed


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("-")]
    project = os.path.realpath(args[0] if args else os.getcwd())
    if os.path.realpath(project) == DEVKIT:
        return 0                        # the DevKit's own checkout loads its files directly
    if "--check" in argv:
        bad = stale(project)
        if bad and "--quiet" not in argv:
            print("stale: " + ", ".join(n if n.startswith("AGENTS.md") else f"{CONTEXT_DIR}/{n}" for n in bad))
        return 1 if bad else 0
    changed = sync(project, agents_md="--context-only" not in argv)
    if changed and "--quiet" not in argv:
        ctx = [n for n in changed if n != "AGENTS.md"]
        if ctx:
            sizes = ", ".join(f"{n} {os.path.getsize(os.path.join(project, CONTEXT_DIR, n)) // 1024} KB" for n in ctx)
            print(f"  - {CONTEXT_DIR}/: {sizes}")
        if "AGENTS.md" in changed:
            print("  - AGENTS.md: DevKit essentials section refreshed")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
