#!/usr/bin/env python3
"""rules_index.py <project> — print the index of the project tier's rules.

One line per section of every rule file in .agents/local/rules/ — headings (#, ##, ###)
and the numbered rules of a numbered rule list ("7. **CẤM TUYỆT ĐỐI remount …**") — with
the line range to open it (`sed -n 'a,bp' <path>`, run from the project root).
context_sync.py writes it to .agents/context/rules-index.md, which the AGENTS.md block
imports instead of every rule file: the lead sentence of each rule stays in front of the
agent at every session start for a fraction of the size, and the prompt hook names the
section that matches a request (scripts/rule_context.py).
"""
import os
import re
import sys

HEADING = re.compile(r"^(#{1,3})\s+(.+?)\s*#*\s*$")
NUMBERED = re.compile(r"^(\d{1,3})\.\s+(?:\*\*(.+?)\*\*|(.+))")
MAX_TITLE = 150
INDEX_NAME = "INDEX.md"                 # never indexed (an early 1.3 build wrote it here)
GENERATED_MARK = "(generated by the DevKit"


def sections(path):
    """[(start, end, level, title)] of one rule file; code fences and HTML comments skipped."""
    lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    # A file whose numbered items carry bold leads is a numbered rule list: every
    # top-level numbered item is a rule then, bold or not (Geely §4.4 has no bold lead).
    rule_list = any((m := NUMBERED.match(l)) and m.group(2) for l in lines)
    marks, fence, comment = [], False, False
    for i, line in enumerate(lines, 1):
        s = line.strip()
        if s.startswith("```"):
            fence = not fence
            continue
        if "<!--" in s and "-->" not in s:
            comment = True
        if comment:
            comment = "-->" not in s
            continue
        if fence:
            continue
        m = HEADING.match(line)
        if m:
            marks.append((i, len(m.group(1)), m.group(2)))
            continue
        m = NUMBERED.match(line)
        if m and rule_list:             # the lead of a numbered rule is the rule itself
            lead = m.group(2) or " ".join(m.group(3).split()[:16])
            marks.append((i, 4, f"{m.group(1)}. {lead}"))
    out = []
    for n, (start, level, title) in enumerate(marks):
        end = len(lines)
        for nxt in marks[n + 1:]:
            if nxt[1] <= level or level == 4:
                end = nxt[0] - 1
                break
        title = re.sub(r"[`*]", "", title).strip()
        out.append((start, end, level, title[:MAX_TITLE] + ("…" if len(title) > MAX_TITLE else "")))
    return out


def rule_files(project):
    root = os.path.join(project, ".agents", "local", "rules")
    files = []
    for d, dirs, names in os.walk(root):
        dirs[:] = sorted(x for x in dirs if not x.startswith("."))
        for n in sorted(names):
            if n.endswith((".md", ".mdc")) and n != INDEX_NAME and not re.search(r"_\d{8}_\d{6}", n):
                files.append(os.path.join(d, n))
    return root, files


def build(project):
    """The index text, or None when the project has no rule files."""
    root, files = rule_files(project)
    if not files:
        return None
    out = [f"# Project rules — index {GENERATED_MARK}; do not edit)", "",
           "Each line is a section of `.agents/local/rules/`. The bold lead of a numbered rule",
           "is the rule itself; open the section (`sed -n` from the project root) before",
           "working in that area. The prompt hook also names the sections that match a request.", ""]
    for f in files:
        rel = os.path.relpath(f, project)
        out.append(f"## {os.path.basename(f)} — `{rel}`")
        for start, end, level, title in sections(f):
            indent = "  " * max(0, min(level, 3) - 1)
            out.append(f"{indent}- {title} — `sed -n '{start},{end}p' {rel}`")
        out.append("")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = build(os.path.realpath(sys.argv[1] if len(sys.argv) > 1 else os.getcwd()))
    sys.stdout.write(text or "")
